MAPA_REGIOES = {
    'AC': 'Norte', 'AP': 'Norte', 'AM': 'Norte', 'PA': 'Norte', 'RO': 'Norte', 'RR': 'Norte', 'TO': 'Norte',
    'AL': 'Nordeste', 'BA': 'Nordeste', 'CE': 'Nordeste', 'MA': 'Nordeste', 'PB': 'Nordeste', 'PE': 'Nordeste', 'PI': 'Nordeste', 'RN': 'Nordeste', 'SE': 'Nordeste',
    'DF': 'Centro-Oeste', 'GO': 'Centro-Oeste', 'MT': 'Centro-Oeste', 'MS': 'Centro-Oeste',
    'ES': 'Sudeste', 'MG': 'Sudeste', 'RJ': 'Sudeste', 'SP': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul'
}

CARGOS_GERENCIAIS = ['GERENTE', 'DIRETOR', 'CONTROLLER', 'CHEF EXECUTIVO DE COZINHA', 'SUPERVISOR']

BAIRROS_RIO = {
    'Rio_Zona Sul': {'BOTAFOGO', 'CATETE', 'COPACABANA', 'COSME VELHO', 'FLAMENGO', 'GÁVEA', 'GLÓRIA', 'HUMAITÁ', 'IPANEMA', 'JARDIM BOTÂNICO', 'LAGOA', 'LARANJEIRAS', 'LEBLON', 'LEME', 'SÃO CONRADO', 'URCA', 'VIDIGAL'},
    'Rio_Centro': {'BONSUCESSO', 'BANCÁRIOS', 'CACUIA', 'CIDADE UNIVERSITÁRIA', 'COCOTÁ', 'FREGUESIA (ILHA)', 'JARDIM CARIOCA', 'JARDIM GUANABARA', 'MONERÓ', 'PITANGUEIRAS', 'PRAIA DA BANDEIRA', 'RIBEIRA', 'ZUMBI', 'CAJU', 'CATUMBI', 'CENTRO', 'CIDADE NOVA', 'ESTÁCIO', 'GAMBOA', 'LAPA', 'MANGUEIRA', 'PAQUETÁ', 'RIO COMPRIDO', 'SANTA TERESA', 'SANTO CRISTO', 'SAÚDE', 'VASCO DA GAMA', 'GAMBOA/SAUDE', 'GLORIA'},
    'Rio_Zona Norte': {'ABOLIÇÃO', 'ÁGUA SANTA', 'ACÁRI', 'ALDEIA CAMPISTA', 'ALTO DA BOA VISTA', 'ANCHIETA', 'ANDARAÍ', 'BANGU', 'BARROS FILHO', 'BENTO RIBEIRO', 'BRÁS DE PINA', 'CACHAMBI', 'CAMPO DOS AFONSOS', 'CAMPINHO', 'CASCADURA', 'CAVALCANTI', 'COELHO NETO', 'COLÉGIO', 'COMPLEXO DO ALEMÃO', 'CORDOVIL', 'COSTA BARROS', 'DEL CASTILHO', 'DEODORO', 'ENCANTADO', 'ENGENHO DA RAINHA', 'ENGENHO DE DENTRO', 'ENGENHO NOVO', 'GRAJAÚ', 'GUADALUPE', 'HIGIENÓPOLIS', 'HONÓRIO GURGEL', 'INHAÚMA', 'IRAJÁ', 'JACARÉ', 'JACAREZINHO', 'JARDIM AMÉRICA', 'LINS DE VASCONCELOS', 'MADUREIRA', 'MAGALHÃES BASTOS', 'MARACANÃ', 'MARECHAL HERMES', 'MARIA DA GRAÇA', 'MÉIER', 'OLARIA', 'OSWALDO CRUZ', 'PARADA DE LUCAS', 'PARQUE ANCHIETA', 'PARQUE COLÚMBIA', 'PAVUNA', 'PACIÊNCIA', 'PADRE MIGUEL', 'PENHA', 'PENHA CIRCULAR', 'PIEDADE', 'PILARES', 'PRAÇA DA BANDEIRA', 'PRAÇA SECA', 'QUINTINO BOCAIUVA', 'RAMOS', 'REALENGO', 'RIACHUELO', 'RICARDO DE ALBUQUERQUE', 'ROCHA', 'ROCHA MIRANDA', 'SAMPAIO', 'SÃO FRANCISCO XAVIER', 'SENADOR CAMARÁ', 'SENADOR VASCONCELOS', 'SANTÍSSIMO', 'TODOS OS SANTOS', 'TOMÁS COELHO', 'TURIAÇU', 'VILA DA PENHA', 'VILA ISABEL', 'VILA KOSMOS', 'VILA MILITAR', 'VILA VALQUEIRE', 'VICENTE DE CARVALHO', 'VIGÁRIO GERAL', 'VISTA ALEGRE', 'TIJUCA', 'SAO CRISTOVAO', 'ROCINHA', 'ENGENHEIRO LEAL', 'MARE', 'OLINDA', 'ACARI', 'MANGUINHOS', 'MARUREIRA', 'JACARE', 'COLEGIO', 'BAIRRO MEIER', 'QUINTINO', 'GALEÃO', 'PORTUGUESA', 'TAUÁ', 'TUBIACANGA', 'BENFICA', 'HIGIENOPOLIS', 'MARÉ', 'TOMAS COELHO', 'MAGALHAES BASTOS'},
    'Rio_Zona Oeste': {'ANIL', 'BARRA DA TIJUCA', 'BARRA DE GUARATIBA', 'CAMORIM', 'CIDADE DE DEUS', 'CURICICA', 'FREGUESIA (JACAREPAGUÁ)', 'GARDÊNIA AZUL', 'GRUMARI', 'ITANHANGÁ', 'JACAREPAGUÁ', 'JOÁ', 'PECHINCHA', 'RECREIO DOS BANDEIRANTES', 'TANQUE', 'TAQUARA', 'VARGEM GRANDE', 'VARGEM PEQUENA', 'CAMPO GRANDE', 'SANTISSIMO', 'SENADOR CAMARA', 'COSMOS', 'INHOAIBA', 'GUARATIBA', 'SEPETIBA', 'SANTA CRUZ', 'AUGUSTO VASCONCELOS', 'RIO DAS PEDRAS', 'MUZEMA', 'CHATUBA', 'GARDENIA AZUL', 'JACAREPAGUA', 'BARBANTE', 'FREGUESIA'}
}

OUTRAS_LOCALIDADES = {
    'NOVA ERA': 'Nova Iguaçu', 'AUSTIN': 'Nova Iguaçu', 'XANGRILÁ': 'Belford Roxo',
    'MESQUITA': 'Mesquita', 'SANTO EXPEDITO': 'Queimados', 'NILÓPOLIS': 'Nilópolis'
}